image:
  file: .gitpod/Dockerfile
tasks:
    - init: cd counter && cargo build
      command: |
        echo $SOLANA_KEY | base64 -d  > /home/gitpod/.config/solana/id.json && solana airdrop 2
        cd counter